name: Actualizar la imagen docker en Docker Hub

on:
  push:
    paths:
      - "Dockerfile"
      - "package.json"
      - "yarn.lock"

jobs:
  push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Actualizar
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: "carlosse/app-chores:latest"